name: 'Build Gradle Edit'
description: ''
author: 'OnekeyHq'
inputs:
  versionCode:
    description: 'versionCode'
    required: true
  versionName:
    description: 'versionName'
    required: true
  android_dir:
    description: 'source dir'
    default: './'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
