name: 'Build Plist Edit'
description: ''
author: 'OnekeyHq'
inputs:
  buildNumber:
    description: 'buildNumber'
    required: true
  versionName:
    description: 'versionName'
    required: true
  projectName:
    description: 'projectName'
    required: true
  dir:
    description: 'source dir'
    default: './'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
