name: 'Slack notify webhook'
description: 'Send notifications via webhooks'
inputs:
  secret-key:
    description: 'Secret key for the Github action signature'
    required: true
  web-hook-url:
    description: 'Webhook URL'
    required: true
  artifact-type:
    description: 'Type of the artifact'
    required: true
  artifact-name:
    description: 'Name of the artifact'
    required: true
  artifact-bundle-id:
    description: 'Bundle ID of the artifact'
    required: true
  artifact-version-name:
    description: 'Version name of the artifact'
    required: true
  artifact-version-code:
    description: 'Version code of the artifact'
    required: true
  artifact-download-url:
    description: 'Download URL of the artifact'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
